### PR TITLE
Updates : sfdump, sfgetset, sfassets, and vars snippets

### PR DESCRIPTION
**Pull request by PurpleBabar**
Minor upgrades

### CODE REVIEW

**Comment by pylebecq** [comment]
Hey, thank you for contributing.

I don't understand why you added so many snippets related to doctrine2 annotations. We already have many of them, check this out: https://github.com/raulfraile/sublime-symfony2/tree/master/Snippets/Doctrine/Annotations .
Also, could you please update the description of the assetic related snippets ? They are all the same for now. Please try to keep the description "hierarchy" we used, like `Symfony2 / Twig / Template / XXX` for stuff going to be put in twig templates.

**Comment by PurpleBabar** [comment]
Hi :) thx for the reply, actually i hesitated to override your annotations snippets, because what i find useful in those i added is the fact that you have the annotations and the variable declaration too, plus with regex you have your variabel name correctly setted for mysql. For the doc i will gladly update it, i tried to respect categories you setted, but if i failed somehow could you tell me whose snippets you'd like to change category ? thx :)

**Comment by PurpleBabar** [comment]
Hi, thx for responding :)

For the vars snippets, i hesitated to override your annotations snippets giving them the var part. I acutally like the fact that the var comes with the annotations and all is made by simply typing your var name (thx to regex, the var name is normalized for mysql in the annotation). Should i override or let them in another folder ?
I tried to respect your hierarchy, if somehow i failed, please tell me, and i'll gladly change it :)
For the assetic snippets i didn't describes them but i putted the results (that are differents ;) )
Thx for your response ;)

**Comment by pylebecq** [comment]
For the hierarchy, you only have to fix three of your snippets:
`asset` -> `Symfony2 / Twig / Template / Asset function`
`asseticcss` -> `Symfony2 / Twig / Template / Assetic CSS tag`
`asseticjs` -> `Symfony2 / Twig / Template / Assetic JS tag`

Snippets are made to reduce typing. So I think it would be a good idea to include the property generation in the snippets. The disadvantage I can see:
- People will not always want private properties.
- People will not always want this naming for the columns names.
These two issues could be solved by providing additional field markers, surrounding the private word and the generated column name. It's not a big deal then.

So if you don't mind, could you please override already provided snippets? Be sure to override all of them though, because I don't want to have two different behaviors.

**Comment by BabarMajes** [comment]
No problem i'll overwrite them, should i keep the Tabtrigger to sf<type>column ?

**Comment by pylebecq** [comment]
Yes. Just replace the `<content>` tag with your code, it will be fine. Thanks.

**Comment by PurpleBabar** [comment]
Did it :) Changed the README too :) hope it's ok :)

**Comment by pylebecq** [comment]
Thanks.

**Pull request merged**
